--insert into scores (id, name, distance) values (1, 'Alex', 1.0);
--insert into scores (id, name, distance) values (2, 'Bob', 2.0 );
--insert into scores (id, name, distance) values (3, 'Carol', 3.0);
--insert into scores (id, name, distance) values (4, 'Daisy', 4.0);
--insert into scores (id, name, distance) values ('Ernie', 6.0);
insert into scores (id, game, name, distance, time) values (1, 5, 'Alex', 1.0, '2022-01-02');
insert into scores (id, game, name, distance, time) values (2, 6, 'Bob', 2.0, '2022-01-02T10:07');
--insert into scores (id, name, distance, time) values (3, 'Carol', 3.0, '2022-01-02');
--insert into scores (id, name, distance, time) values (4, 'Daisy', 4.0, '2022-01-02');
--insert into scores (id, name, distance, time) values (5, 'Ernie', 6.0, '2022-01-03');
