# This workflow compiles a zip for elastic beanstalk

name: 'zip for eb'

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  kame-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get version code
        id: get_version_code
        env:
          FILE: src/main/resources/application.properties
        run: |
          VERSION=$(grep -Po -m 1 "(?<=info.app.version=).*" $FILE)
          echo "::set-output name=version::$VERSION"

      # sets NEW_VERSION_NAME
      - name: output version name
        run : |
          echo "steps.get_version_code.outputs.version"

      - name: checkout new branch
        run: git checkout -b release/v${{ steps.get_version_code.outputs.version }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: |
            echo "$(pwd)"
            chmod +x gradlew
      - name: compile jar
        run: |
            echo "$(pwd)"      
            ./gradlew bootJar
            cp build/libs/circle-escape-server-0.0.1-SNAPSHOT.jar .
            zip circle-escape-server.zip -r .ebextensions circle-escape-server-0.0.1-SNAPSHOT.jar
            rm circle-escape-server-0.0.1-SNAPSHOT.jar

      - name: init git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - uses: nelonoel/branch-name@v1
      - name: print branch name
        run: |
          echo release/v${{ steps.get_version_code.outputs.version }}
          echo ${BRANCH_NAME}

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/v${{ steps.get_version_code.outputs.version }}
        
          
